### ISSUE TITLE
would you please provide a rosbag?

### ISSUE THREAD

**Issue by WANG-KX** [robustrobotics/flame_ros#1]
A rosbag would help me understand what topic to provide for flame_ros and in what format (especially the camera info and tf information).
Thanks!

**Comment by wngreene** [comment]
The `Online Processing` section in the readme should give more info on how to run the online nodelet with bagged data, but the TUM bag here: 

https://vision.in.tum.de/rgbd/dataset/freiburg3/rgbd_dataset_freiburg3_structure_texture_far.bag

should help you get started.
