### ISSUE TITLE
Memory leak somewhere

### ISSUE THREAD

**Issue by gajena** [robustrobotics/flame_ros#7]
I was running online and offline but in both cases, my ram was getting full.
I tried to disable all output but this thing is still there.
Ram: 8Gb
CPU: i7 quadcore

**Comment by bednarhonza** [comment]
@gajena Have you solved this issue somehow? I have faced the same problem but only in online processing.

EDIT: My RAM is getting full for the offline datasets as well. However, it is a slower process than during online processing.

Thanks!

**Comment by gajena** [comment]
@bednarhonza No, I was not able to resolve this issue. But it was a long time ago ... If you are not in a hurry, then maybe I can try to figure it out.

**Comment by bednarhonza** [comment]
@gajena That would be awesome! I tried to debug it with valgrind but no success yet. Please let me know if you have any updates.

**Comment by gajena** [comment]
@bednarhonza Found the issue, in flame_ws/src/flame/src/flame/flame.cc:158 
`pfs_[fnew_->id] = fnew_`
since `pfs_` is a map without any size check and it takes the ownership of this shared_ptr `fnew_` and that's why memory usage are increasing continously since there is no releasing of shared_ptr from map. For just to check that my observation is correct I applied simple size check and now it does not crosses 400MB memory.
`    auto it  = pfs_.cbegin();
    if (it != pfs_.cend() && pfs_.size() > 30) {
      pfs_.erase(it->first);
    }
    pfs_.insert(std::make_pair(fnew_->id, fnew_));`

**Comment by bednarhonza** [comment]
@gajena Amazing thanks for your help! I really appreciate that.

I was wondering, that this, sort of pruning, should be be handled by `void Flame::prunePoseFrames(const std::vector<uint32_t>& pfs_to_keep)`. However, this function is triggered only by incoming pose messages. If I understood well, the function tries to pair the IDs from pose messages and frames to find the ones to keep and throw the others. However, the IDs for both poses and frames are made by sequence numbers of the ROS messages. That does not make sense to me.
The `prunePoseFrames` function handles the other structures as well to clean them from pruned frames. Should I handle this as well? I have noticed, that the algorithm seems to work without this perfect as well.

Thank you!
Jan

**Comment by bednarhonza** [comment]
@gajena I have found out that the poses have to be pruned, to be completely removed from the other structures. Here is the final code:
flame_ws/src/flame/src/flame/flame.cc:155
`
  if (is_poseframe) {
    // Add to poseframes.
    pfs_mtx_.lock();

    auto it = pfs_.cbegin();

    if (it != pfs_.cend() && pfs_.size() > 30)
    {
      std::vector<uint32_t> pf_ids(pfs_.size());
      pf_ids.clear();
      // Delete the last one by skipping
      it++;
      while(it != pfs_.cend())
      {
          pf_ids.push_back(it->first); 
          it++;
      }
      prunePoseFrames(pf_ids);
    }
    pfs_.insert(std::make_pair(fnew_->id, fnew_));
    pfs_mtx_.unlock();

    curr_pf_ = fnew_;
  }
`

Next, the mutex in prunePoseFrames has to be deleted, because it is already in use.
flame_ws/src/flame/src/flame/flame.cc:604
`  /* std::lock_guard<std::mutex> pfs_lock(pfs_mtx_); */
`

**Comment by gajena** [comment]
Sorry, I was busy. I did not check your code, is it working fine?

**Comment by bednarhonza** [comment]
I have been busy with other work lately, but I have tested it on the machine hall datasets and it worked. The result was the same and the memory was not leaking..
